// Code generated by cmd/optionsgen from apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 PUT /nodes/{node}/config); DO NOT EDIT.

package node

import "github.com/fivetwenty-io/pmx-cli/internal/optionschema"

// configSchemas describes every settable option from the PVE API schema for
// PUT /nodes/{node}/config, in lexical order by API key.
var configSchemas = []optionschema.Schema{
	{
		Name:        "acme",
		Flag:        "acme",
		Type:        "string",
		Description: "Node specific ACME settings.",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "account",
				Type:        "string",
				Default:     "default",
				Description: "ACME account config file name.",
			},
			{
				Name:        "domains",
				Type:        "string",
				Description: "List of domains for this node's ACME certificate",
			},
		},
	},
	{
		Name:        "acmedomain[n]",
		Flag:        "acme-domain",
		Type:        "string",
		Description: "ACME domain and validation plugin",
		Indexed:     true,
		SubKeys: []optionschema.SubKey{
			{
				Name:        "alias",
				Type:        "string",
				Description: "Alias for the Domain to verify ACME Challenge over DNS",
			},
			{
				Name:        "domain",
				Type:        "string",
				Description: "domain for this node's ACME certificate",
				Required:    true,
			},
			{
				Name:        "plugin",
				Type:        "string",
				Default:     "standalone",
				Description: "The ACME plugin ID",
			},
		},
	},
	{
		Name:        "ballooning-target",
		Flag:        "ballooning-target",
		Type:        "integer",
		Default:     "80",
		Minimum:     "0",
		Maximum:     "100",
		Description: "RAM usage target for ballooning (in percent of total memory)",
	},
	{
		Name:        "description",
		Flag:        "description",
		Type:        "string",
		Description: "Description for the Node. Shown in the web-interface node notes panel. This is saved as comment inside the configuration file.",
	},
	{
		Name:        "location",
		Flag:        "location",
		Type:        "string",
		Description: "The location of the node. Overrides the default from the datacenter config.",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "latitude",
				Type:        "number",
				Minimum:     "-90",
				Maximum:     "90",
				Description: "The latitude of the nodes location in degrees.",
				Required:    true,
			},
			{
				Name:        "longitude",
				Type:        "number",
				Minimum:     "-180",
				Maximum:     "180",
				Description: "The longitude of the nodes location in degrees.",
				Required:    true,
			},
			{
				Name:        "name",
				Type:        "string",
				Description: "The name of the location of this node",
			},
		},
	},
	{
		Name:        "startall-onboot-delay",
		Flag:        "startall-onboot-delay",
		Type:        "integer",
		Default:     "0",
		Minimum:     "0",
		Maximum:     "300",
		Description: "Initial delay in seconds, before starting all the Virtual Guests with on-boot enabled.",
	},
	{
		Name:        "wakeonlan",
		Flag:        "wakeonlan",
		Type:        "string",
		Description: "Node specific wake on LAN settings.",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "bind-interface",
				Type:        "string",
				Default:     "The interface carrying the default route",
				Description: "Bind to this interface when sending wake on LAN packet",
			},
			{
				Name:        "broadcast-address",
				Type:        "string",
				Default:     "255.255.255.255",
				Description: "IPv4 broadcast address to use when sending wake on LAN packet",
			},
			{
				Name:        "mac",
				Type:        "string",
				Description: "MAC address for wake on LAN",
				Required:    true,
			},
		},
	},
}
