// Code generated by cmd/optionsgen from apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 PUT /nodes/{node}/firewall/options); DO NOT EDIT.

package node

import "github.com/fivetwenty-io/pve-cli/internal/optionschema"

// firewallOptionSchemas describes every settable option from the PVE API schema for
// PUT /nodes/{node}/firewall/options, in lexical order by API key.
var firewallOptionSchemas = []optionschema.Schema{
	{
		Name:        "enable",
		Flag:        "enable",
		Type:        "boolean",
		Default:     "true",
		Description: "Enable host firewall rules.",
	},
	{
		Name:        "log_level_forward",
		Flag:        "log-level-forward",
		Type:        "string",
		Enum:        []string{"emerg", "alert", "crit", "err", "warning", "notice", "info", "debug", "nolog"},
		Description: "Log level for forwarded traffic.",
	},
	{
		Name:        "log_level_in",
		Flag:        "log-level-in",
		Type:        "string",
		Enum:        []string{"emerg", "alert", "crit", "err", "warning", "notice", "info", "debug", "nolog"},
		Description: "Log level for incoming traffic.",
	},
	{
		Name:        "log_level_out",
		Flag:        "log-level-out",
		Type:        "string",
		Enum:        []string{"emerg", "alert", "crit", "err", "warning", "notice", "info", "debug", "nolog"},
		Description: "Log level for outgoing traffic.",
	},
	{
		Name:        "log_nf_conntrack",
		Flag:        "log-nf-conntrack",
		Type:        "boolean",
		Default:     "false",
		Description: "Enable logging of conntrack information.",
	},
	{
		Name:        "ndp",
		Flag:        "ndp",
		Type:        "boolean",
		Default:     "true",
		Description: "Enable NDP (Neighbor Discovery Protocol).",
	},
	{
		Name:        "nf_conntrack_allow_invalid",
		Flag:        "nf-conntrack-allow-invalid",
		Type:        "boolean",
		Default:     "false",
		Description: "Allow invalid packets on connection tracking.",
	},
	{
		Name:        "nf_conntrack_helpers",
		Flag:        "nf-conntrack-helpers",
		Type:        "string",
		Description: "Enable conntrack helpers for specific protocols. Supported protocols: amanda, ftp, irc, netbios-ns, pptp, sane, sip, snmp, tftp",
	},
	{
		Name:        "nf_conntrack_max",
		Flag:        "nf-conntrack-max",
		Type:        "integer",
		Default:     "262144",
		Minimum:     "32768",
		Description: "Maximum number of tracked connections.",
	},
	{
		Name:        "nf_conntrack_tcp_timeout_established",
		Flag:        "nf-conntrack-tcp-timeout-established",
		Type:        "integer",
		Default:     "432000",
		Minimum:     "7875",
		Description: "Conntrack established timeout.",
	},
	{
		Name:        "nf_conntrack_tcp_timeout_syn_recv",
		Flag:        "nf-conntrack-tcp-timeout-syn-recv",
		Type:        "integer",
		Default:     "60",
		Minimum:     "30",
		Maximum:     "60",
		Description: "Conntrack syn recv timeout.",
	},
	{
		Name:        "nftables",
		Flag:        "nftables",
		Type:        "boolean",
		Default:     "false",
		Description: "Enable nftables based firewall (tech preview)",
	},
	{
		Name:        "nosmurfs",
		Flag:        "nosmurfs",
		Type:        "boolean",
		Description: "Enable SMURFS filter.",
	},
	{
		Name:        "protection_synflood",
		Flag:        "protection-synflood",
		Type:        "boolean",
		Default:     "false",
		Description: "Enable synflood protection",
	},
	{
		Name:        "protection_synflood_burst",
		Flag:        "protection-synflood-burst",
		Type:        "integer",
		Default:     "1000",
		Description: "Synflood protection rate burst by ip src.",
	},
	{
		Name:        "protection_synflood_rate",
		Flag:        "protection-synflood-rate",
		Type:        "integer",
		Default:     "200",
		Description: "Synflood protection rate syn/sec by ip src.",
	},
	{
		Name:        "smurf_log_level",
		Flag:        "smurf-log-level",
		Type:        "string",
		Enum:        []string{"emerg", "alert", "crit", "err", "warning", "notice", "info", "debug", "nolog"},
		Description: "Log level for SMURFS filter.",
	},
	{
		Name:        "tcp_flags_log_level",
		Flag:        "tcp-flags-log-level",
		Type:        "string",
		Enum:        []string{"emerg", "alert", "crit", "err", "warning", "notice", "info", "debug", "nolog"},
		Description: "Log level for illegal tcp flags filter.",
	},
	{
		Name:        "tcpflags",
		Flag:        "tcpflags",
		Type:        "boolean",
		Default:     "false",
		Description: "Filter illegal combinations of TCP flags.",
	},
}
