// Command docgen generates roff man pages for every pmx persona command tree
// (pmx, pve, pbs, pdm) using cobra/doc. It builds each tree exactly the way
// cmd/pmx does (internal/persona wiring, zero-value deps, no network, no
// config) and writes man1/ pages under -out. Pages are reproducible: the
// date comes from -date (never wall clock), env-derived flag defaults are
// rewritten to portable literals, and PMX_* variables are cleared first.
//
// Usage:
//
//	go run ./cmd/docgen -out ./dist/man -version v1.2.3 -date 2026-07-10
package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/fivetwenty-io/pmx-cli/internal/cli"
	"github.com/fivetwenty-io/pmx-cli/internal/persona"
)

// fallbackDate keeps dev-box output byte-deterministic when no -date is given.
const fallbackDate = "1970-01-01"

type runOpts struct {
	out      string
	personas []string
	version  string
	date     string
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("docgen: ")

	out := flag.String("out", "./dist/man", "output root (man1/ and man5/ are created beneath it)")
	version := flag.String("version", "dev", "version stamped into each page's .TH header")
	date := flag.String("date", fallbackDate, "page date, RFC3339 or YYYY-MM-DD (never wall clock)")
	personasFlag := flag.String("personas", strings.Join(persona.Names(), ","),
		"comma-separated persona trees to generate")
	flag.Parse()

	if err := run(runOpts{
		out:      *out,
		personas: strings.Split(*personasFlag, ","),
		version:  *version,
		date:     *date,
	}); err != nil {
		log.Fatal(err)
	}
}

func run(opts runOpts) error {
	for _, k := range []string{"PMX_CONTEXT", "PMX_NODE", "PMX_OUTPUT", "PMX_TOKEN", "PMX_TOKEN_SECRET"} {
		os.Unsetenv(k)
	}

	known := map[string]bool{}
	for _, n := range persona.Names() {
		known[n] = true
	}

	man1 := filepath.Join(opts.out, "man1")
	if err := os.MkdirAll(man1, 0o755); err != nil {
		return err
	}

	hdr, err := header(opts.version, opts.date)
	if err != nil {
		return err
	}

	for _, name := range opts.personas {
		if !known[name] {
			return fmt.Errorf("unknown persona %q (valid: %s)", name, strings.Join(persona.Names(), ", "))
		}
		root, cleanup := buildRoot(name)
		disableAutoGen(root)
		sanitizeFlags(root)
		if err := doc.GenManTree(root, hdr, man1); err != nil {
			cleanup()
			return fmt.Errorf("persona %s: %w", name, err)
		}
		cleanup()
		log.Printf("persona %s -> %s", name, man1)
	}
	return nil
}

// buildRoot assembles the full command tree for a persona, mirroring the
// first half of cli.Execute (root + flags, then group factories).
func buildRoot(name string) (*cobra.Command, func()) {
	root, cleanup := cli.NewRootCmd(name)
	root.SetContext(context.Background())
	cli.AddGroups(root, &cli.Deps{}, persona.Factories(name))
	return root, cleanup
}

// header builds the shared .TH header. Date parsing accepts RFC3339 or
// YYYY-MM-DD; anything else falls back to fallbackDate so output stays
// deterministic rather than failing a release over a formatting nit.
func header(version, rawDate string) (*doc.GenManHeader, error) {
	t, err := time.Parse(time.RFC3339, rawDate)
	if err != nil {
		t, err = time.Parse("2006-01-02", rawDate)
	}
	if err != nil {
		t, _ = time.Parse("2006-01-02", fallbackDate)
	}
	return &doc.GenManHeader{
		Section: "1",
		Source:  "pmx " + version,
		Manual:  "pmx Manual",
		Date:    &t,
	}, nil
}

// disableAutoGen drops the HISTORY section and "Auto generated by spf13/cobra"
// footer from every page (noise, plus a second embedded date).
func disableAutoGen(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, c := range cmd.Commands() {
		disableAutoGen(c)
	}
}

// sanitizeFlags rewrites machine/env-derived persistent-flag defaults to
// portable literals so pages neither leak the builder's $HOME nor vary by
// environment. Man-page cosmetics only; runtime flags are untouched.
func sanitizeFlags(root *cobra.Command) {
	if f := root.PersistentFlags().Lookup("config"); f != nil {
		f.DefValue = "~/.config/pmx/config.yml"
	}
	if f := root.PersistentFlags().Lookup("node"); f != nil {
		f.DefValue = ""
	}
	if f := root.PersistentFlags().Lookup("output"); f != nil {
		f.DefValue = "table"
	}
}
