// Command docgen generates roff man pages for every pmx persona command tree
// (pmx, pve, pbs, pdm) using cobra/doc. It builds each tree exactly the way
// cmd/pmx does (internal/persona wiring, zero-value deps, no network, no
// config) and writes man1/ pages under -out. Pages are reproducible: the
// date comes from -date (never wall clock), env-derived flag defaults are
// rewritten to portable literals, and PMX_* variables are cleared first.
//
// Usage:
//
//	go run ./cmd/docgen -out ./dist/man -version v1.2.3 -date 2026-07-10
package main

import (
	"bytes"
	"context"
	"embed"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/cpuguy83/go-md2man/v2/md2man"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/fivetwenty-io/pmx-cli/internal/cli"
	"github.com/fivetwenty-io/pmx-cli/internal/persona"
)

// pages embeds the hand-authored roff fragments spliced into generated pages.
// cobra/doc has no hook for ENVIRONMENT/FILES/EXIT STATUS, so these sections
// are authored in markdown, rendered with the same md2man cobra uses
// internally, and spliced into the four persona root pages by
// injectRootSections.
//
//go:embed pages/root-sections.md
var pages embed.FS

// fallbackDate keeps dev-box output byte-deterministic when no -date is given.
const fallbackDate = "1970-01-01"

type runOpts struct {
	out      string
	personas []string
	version  string
	date     string
}

func main() {
	log.SetFlags(0)
	log.SetPrefix("docgen: ")

	out := flag.String("out", "./dist/man", "output root (man1/ and man5/ are created beneath it)")
	version := flag.String("version", "dev", "version stamped into each page's .TH header")
	date := flag.String("date", fallbackDate, "page date, RFC3339 or YYYY-MM-DD (never wall clock)")
	personasFlag := flag.String("personas", strings.Join(persona.Names(), ","),
		"comma-separated persona trees to generate")
	flag.Parse()

	if err := run(runOpts{
		out:      *out,
		personas: strings.Split(*personasFlag, ","),
		version:  *version,
		date:     *date,
	}); err != nil {
		log.Fatal(err)
	}
}

func run(opts runOpts) error {
	for _, k := range []string{"PMX_CONTEXT", "PMX_NODE", "PMX_OUTPUT", "PMX_TOKEN", "PMX_TOKEN_SECRET"} {
		os.Unsetenv(k)
	}

	known := map[string]bool{}
	for _, n := range persona.Names() {
		known[n] = true
	}

	man1 := filepath.Join(opts.out, "man1")
	if err := os.MkdirAll(man1, 0o755); err != nil {
		return err
	}

	hdr, err := header(opts.version, opts.date)
	if err != nil {
		return err
	}

	for _, name := range opts.personas {
		if !known[name] {
			return fmt.Errorf("unknown persona %q (valid: %s)", name, strings.Join(persona.Names(), ", "))
		}
		root, cleanup := buildRoot(name)
		disableAutoGen(root)
		sanitizeFlags(root)
		if err := doc.GenManTree(root, hdr, man1); err != nil {
			cleanup()
			return fmt.Errorf("persona %s: %w", name, err)
		}
		cleanup()

		rootPage := filepath.Join(man1, name+".1")
		b, err := os.ReadFile(rootPage) //nolint:gosec // G304: rootPage is man1+persona name, not untrusted input
		if err != nil {
			return fmt.Errorf("persona %s: read root page: %w", name, err)
		}
		//nolint:gosec // G306: man pages are world-readable by convention
		if err := os.WriteFile(rootPage, injectRootSections(b), 0o644); err != nil {
			return fmt.Errorf("persona %s: write root page: %w", name, err)
		}

		log.Printf("persona %s -> %s", name, man1)
	}
	return nil
}

// buildRoot assembles the full command tree for a persona, mirroring the
// first half of cli.Execute (root + flags, then group factories).
func buildRoot(name string) (*cobra.Command, func()) {
	root, cleanup := cli.NewRootCmd(name)
	root.SetContext(context.Background())
	cli.AddGroups(root, &cli.Deps{}, persona.Factories(name))
	return root, cleanup
}

// header builds the shared .TH header. Date parsing accepts RFC3339 or
// YYYY-MM-DD; anything else falls back to fallbackDate so output stays
// deterministic rather than failing a release over a formatting nit.
func header(version, rawDate string) (*doc.GenManHeader, error) {
	t, err := time.Parse(time.RFC3339, rawDate)
	if err != nil {
		t, err = time.Parse("2006-01-02", rawDate)
	}
	if err != nil {
		t, _ = time.Parse("2006-01-02", fallbackDate)
	}
	return &doc.GenManHeader{
		Section: "1",
		Source:  "pmx " + version,
		Manual:  "pmx Manual",
		Date:    &t,
	}, nil
}

// disableAutoGen drops the HISTORY section and "Auto generated by spf13/cobra"
// footer from every page (noise, plus a second embedded date).
func disableAutoGen(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, c := range cmd.Commands() {
		disableAutoGen(c)
	}
}

// sanitizeFlags rewrites machine/env-derived persistent-flag defaults to
// portable literals so pages neither leak the builder's $HOME nor vary by
// environment. Man-page cosmetics only; runtime flags are untouched.
func sanitizeFlags(root *cobra.Command) {
	if f := root.PersistentFlags().Lookup("config"); f != nil {
		f.DefValue = "~/.config/pmx/config.yml"
	}
	if f := root.PersistentFlags().Lookup("node"); f != nil {
		f.DefValue = ""
	}
	if f := root.PersistentFlags().Lookup("output"); f != nil {
		f.DefValue = "table"
	}
}

// seeAlsoMarker is the exact roff macro cobra/doc emits for its auto-generated
// SEE ALSO section (verified against actual GenManTree output). Splicing
// before it keeps SEE ALSO auto-generated so persona group lists never go
// stale, while ENVIRONMENT/FILES/EXIT STATUS come from the hand-authored
// fragment below.
const seeAlsoMarker = ".SH SEE ALSO"

// injectRootSections splices the authored ENVIRONMENT/FILES/EXIT STATUS roff
// into a rendered root page immediately before SEE ALSO (appending at the end
// if SEE ALSO is absent), keeping SEE ALSO itself auto-generated by cobra/doc.
//
// pages/root-sections.md opens with a throwaway "# root-sections" heading:
// md2man renders a document's first heading as the .TH title block rather
// than a .SH section, so that heading (and everything before the first real
// .SH) is trimmed away here rather than baked in as a magic byte prefix.
func injectRootSections(page []byte) []byte {
	src, err := pages.ReadFile("pages/root-sections.md")
	if err != nil {
		// Embedded at build time; a missing file is a programmer error, not a
		// runtime condition callers can recover from.
		panic(fmt.Sprintf("docgen: embedded pages/root-sections.md missing: %v", err))
	}
	extra := md2man.Render(src)
	if i := bytes.Index(extra, []byte(".SH ")); i >= 0 {
		extra = extra[i:]
	}

	i := bytes.Index(page, []byte(seeAlsoMarker))
	if i < 0 {
		out := make([]byte, 0, len(page)+len(extra))
		out = append(out, page...)
		return append(out, extra...)
	}
	out := make([]byte, 0, len(page)+len(extra))
	out = append(out, page[:i]...)
	out = append(out, extra...)
	return append(out, page[i:]...)
}
