package storage

import (
	"encoding/json"
	"fmt"

	"github.com/spf13/cobra"

	"github.com/fivetwenty-io/proxmox-apiclient-go/v3/pkg/api/nodes"
	"github.com/fivetwenty-io/proxmox-cli/internal/cli"
	"github.com/fivetwenty-io/proxmox-cli/internal/output"
)

// newStorageRrddataCmd builds `pmx pve storage rrddata <storage>` — structured
// time-series metric data for a storage on the resolved node
// (GET /nodes/{node}/storage/{storage}/rrddata).
func newStorageRrddataCmd() *cobra.Command {
	var (
		timeframe string
		cf        string
	)
	cmd := &cobra.Command{
		Use:   "rrddata <storage>",
		Short: "Show structured time-series metrics for a storage",
		Long: "Retrieve per-interval RRD statistics for a storage on the resolved node. " +
			"--timeframe controls the resolution (hour, day, week, month, year). " +
			"--cf selects the RRD consolidation function (AVERAGE, MAX).",
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := cli.GetDeps(cmd)
			if deps.Node == "" {
				return fmt.Errorf("no node specified: use --node, set PMX_NODE, or configure a default node")
			}
			storage := args[0]

			params := &nodes.ListStorageRrddataParams{
				Timeframe: timeframe,
			}
			if cmd.Flags().Changed("cf") {
				params.Cf = &cf
			}

			resp, err := deps.API.Nodes.ListStorageRrddata(cmd.Context(), deps.Node, storage, params)
			if err != nil {
				return fmt.Errorf("get storage rrddata %q on node %q: %w", storage, deps.Node, err)
			}

			// Decode the slice of raw objects for structured output.
			rows := make([][]string, 0)
			raw := make([]map[string]any, 0)
			if resp != nil {
				for _, item := range *resp {
					var obj map[string]any
					if err := json.Unmarshal(item, &obj); err != nil {
						return fmt.Errorf("decode rrddata entry: %w", err)
					}
					raw = append(raw, obj)
					// Best-effort flat row: time + up to two numeric fields.
					t := scalarString(obj["time"])
					u := scalarString(obj["used"])
					a := scalarString(obj["total"])
					rows = append(rows, []string{t, u, a})
				}
			}

			res := output.Result{
				Headers: []string{"TIME", "USED", "TOTAL"},
				Rows:    rows,
				Raw:     raw,
			}
			return deps.Out.Render(cmd.OutOrStdout(), res, deps.Format)
		},
	}
	fl := cmd.Flags()
	fl.StringVar(&timeframe, "timeframe", "hour", "time frame: hour|day|week|month|year")
	fl.StringVar(&cf, "cf", "", "RRD consolidation function: AVERAGE|MAX")
	return cmd
}

// newStorageRrdCmd builds `pmx pve storage rrd <storage>` — returns the URL of a
// legacy PNG RRD graph for a storage on the resolved node
// (GET /nodes/{node}/storage/{storage}/rrd).
func newStorageRrdCmd() *cobra.Command {
	var (
		timeframe string
		ds        string
		cf        string
	)
	cmd := &cobra.Command{
		Use:   "rrd <storage>",
		Short: "Show the RRD graph URL for a storage (legacy PNG endpoint)",
		Long: "Return the filename (URL) of the RRD PNG graph generated by the PVE server " +
			"for a storage on the resolved node. Most operators should use `rrddata` instead " +
			"for structured data.",
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			deps := cli.GetDeps(cmd)
			if deps.Node == "" {
				return fmt.Errorf("no node specified: use --node, set PMX_NODE, or configure a default node")
			}
			storage := args[0]

			params := &nodes.ListStorageRrdParams{
				Timeframe: timeframe,
				Ds:        ds,
			}
			if cmd.Flags().Changed("cf") {
				params.Cf = &cf
			}

			resp, err := deps.API.Nodes.ListStorageRrd(cmd.Context(), deps.Node, storage, params)
			if err != nil {
				return fmt.Errorf("get storage rrd %q on node %q: %w", storage, deps.Node, err)
			}

			single := map[string]string{"filename": resp.Filename}
			res := output.Result{Single: single, Raw: resp}
			return deps.Out.Render(cmd.OutOrStdout(), res, deps.Format)
		},
	}
	fl := cmd.Flags()
	fl.StringVar(&timeframe, "timeframe", "hour", "time frame: hour|day|week|month|year")
	fl.StringVar(&ds, "ds", "", "datasource name(s) to display (required by PVE API)")
	fl.StringVar(&cf, "cf", "", "RRD consolidation function: AVERAGE|MAX")
	cli.MustMarkRequired(cmd, "ds")
	return cmd
}
