// Code generated by cmd/optionsgen from apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 PUT /cluster/sdn/vnets/{vnet}/firewall/options); DO NOT EDIT.

package sdn

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// vnetFirewallOptionSchemas describes every settable option from the PVE API schema for
// PUT /cluster/sdn/vnets/{vnet}/firewall/options, in lexical order by API key.
var vnetFirewallOptionSchemas = []optionschema.Schema{
	{
		Name:        "enable",
		Flag:        "enable",
		Type:        "boolean",
		Default:     "false",
		Description: "Enable/disable firewall rules.",
	},
	{
		Name:        "log_level_forward",
		Flag:        "log-level-forward",
		Type:        "string",
		Enum:        []string{"emerg", "alert", "crit", "err", "warning", "notice", "info", "debug", "nolog"},
		Description: "Log level for forwarded traffic.",
	},
	{
		Name:        "policy_forward",
		Flag:        "policy-forward",
		Type:        "string",
		Enum:        []string{"ACCEPT", "DROP"},
		Description: "Forward policy.",
	},
}
