// Code generated by cmd/optionsgen from apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 PUT /nodes/{node}/lxc/{vmid}/firewall/options); DO NOT EDIT.

package lxc

import "github.com/fivetwenty-io/pmx-cli/internal/optionschema"

// firewallOptionSchemas describes every settable option from the PVE API schema for
// PUT /nodes/{node}/lxc/{vmid}/firewall/options, in lexical order by API key.
var firewallOptionSchemas = []optionschema.Schema{
	{
		Name:        "dhcp",
		Flag:        "dhcp",
		Type:        "boolean",
		Default:     "false",
		Description: "Enable DHCP.",
	},
	{
		Name:        "enable",
		Flag:        "enable",
		Type:        "boolean",
		Default:     "false",
		Description: "Enable/disable firewall rules.",
	},
	{
		Name:        "ipfilter",
		Flag:        "ipfilter",
		Type:        "boolean",
		Description: "Enable default IP filters. This is equivalent to adding an empty ipfilter-net<id> ipset for every interface. Such ipsets implicitly contain sane default restrictions such as restricting IPv6 link local addresses to the one derived from the interface's MAC address. For containers the configured IP addresses will be implicitly added.",
	},
	{
		Name:        "log_level_in",
		Flag:        "log-level-in",
		Type:        "string",
		Enum:        []string{"emerg", "alert", "crit", "err", "warning", "notice", "info", "debug", "nolog"},
		Description: "Log level for incoming traffic.",
	},
	{
		Name:        "log_level_out",
		Flag:        "log-level-out",
		Type:        "string",
		Enum:        []string{"emerg", "alert", "crit", "err", "warning", "notice", "info", "debug", "nolog"},
		Description: "Log level for outgoing traffic.",
	},
	{
		Name:        "macfilter",
		Flag:        "macfilter",
		Type:        "boolean",
		Default:     "true",
		Description: "Enable/disable MAC address filter.",
	},
	{
		Name:        "ndp",
		Flag:        "ndp",
		Type:        "boolean",
		Default:     "true",
		Description: "Enable NDP (Neighbor Discovery Protocol).",
	},
	{
		Name:        "policy_in",
		Flag:        "policy-in",
		Type:        "string",
		Enum:        []string{"ACCEPT", "REJECT", "DROP"},
		Description: "Input policy.",
	},
	{
		Name:        "policy_out",
		Flag:        "policy-out",
		Type:        "string",
		Enum:        []string{"ACCEPT", "REJECT", "DROP"},
		Description: "Output policy.",
	},
	{
		Name:        "radv",
		Flag:        "radv",
		Type:        "boolean",
		Description: "Allow sending Router Advertisement.",
	},
}
