// Code generated by cmd/optionsgen from pdm-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 PUT /nodes/{node}/config); DO NOT EDIT.

package pdm

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// nodeConfigOptionSchemas describes every settable option from the Proxmox Datacenter Manager API schema for
// PUT /nodes/{node}/config, in lexical order by API key.
var nodeConfigOptionSchemas = []optionschema.Schema{
	{
		Name:        "ciphers-tls-1.2",
		Flag:        "ciphers-tls-1.2",
		Type:        "string",
		Description: "OpenSSL cipher list used by the api server for TLS <= 1.2",
	},
	{
		Name:        "ciphers-tls-1.3",
		Flag:        "ciphers-tls-1.3",
		Type:        "string",
		Description: "OpenSSL ciphersuites list used by the api server for TLS 1.3",
	},
	{
		Name:        "default-lang",
		Flag:        "default-lang",
		Type:        "string",
		Enum:        []string{"ar", "ca", "da", "de", "en", "es", "eu", "fa", "fr", "gl", "he", "hu", "it", "ja", "kr", "nb", "nl", "nn", "pl", "pt_BR", "ru", "sl", "sv", "tr", "zh_CN", "zh_TW"},
		Description: "All available languages in Proxmox. Taken from proxmox-i18n repository. pt_BR, zh_CN, and zh_TW use the same case in the translation files.",
	},
	{
		Name:        "email-from",
		Flag:        "email-from",
		Type:        "string",
		Description: "E-Mail Address.",
	},
	{
		Name:        "http-proxy",
		Flag:        "http-proxy",
		Type:        "string",
		Description: "HTTP proxy configuration [http://]<host>[:port]",
	},
}
