// Code generated by cmd/optionsgen from pdm-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /remotes/remote); DO NOT EDIT.

package pdm

import "github.com/fivetwenty-io/pmx-cli/internal/optionschema"

// remoteOptionSchemas describes every settable option from the PVE API schema for
// POST /remotes/remote, in lexical order by API key.
var remoteOptionSchemas = []optionschema.Schema{
	{
		Name:        "authid",
		Flag:        "authid",
		Type:        "string",
		Description: "Authentication ID",
	},
	{
		Name:        "create-token",
		Flag:        "create-token",
		Type:        "string",
		Description: "If given, create this token on the remote and use it.",
	},
	{
		Name:        "nodes",
		Flag:        "nodes",
		Type:        "array",
		Description: "A list of cluster node addresses.",
	},
	{
		Name:        "type",
		Flag:        "type",
		Type:        "string",
		Default:     "pve",
		Enum:        []string{"pve", "pbs"},
		Description: "The type of a remote entry.",
	},
	{
		Name:        "web-url",
		Flag:        "web-url",
		Type:        "string",
		Description: "Configuration for the Web UI URL link generation.",
	},
}
