// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/datastore); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/pve-cli/internal/optionschema"

// datastoreOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/datastore, in lexical order by API key.
var datastoreOptionSchemas = []optionschema.Schema{
	{
		Name:        "backend",
		Flag:        "backend",
		Type:        "string",
		Description: "Datastore backend config",
	},
	{
		Name:        "backing-device",
		Flag:        "backing-device",
		Type:        "string",
		Description: "The UUID of the filesystem partition for removable datastores.",
	},
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "counter-reset-schedule",
		Flag:        "counter-reset-schedule",
		Type:        "string",
		Description: "Reset notification threshold related counters at specified schedule.",
	},
	{
		Name:        "gc-on-unmount",
		Flag:        "gc-on-unmount",
		Type:        "boolean",
		Description: "Run garbage collection before unmounting a removable datastore.",
	},
	{
		Name:        "gc-schedule",
		Flag:        "gc-schedule",
		Type:        "string",
		Description: "Run garbage collection job at specified schedule.",
	},
	{
		Name:        "keep-daily",
		Flag:        "keep-daily",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of daily backups to keep.",
	},
	{
		Name:        "keep-hourly",
		Flag:        "keep-hourly",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of hourly backups to keep.",
	},
	{
		Name:        "keep-last",
		Flag:        "keep-last",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of backups to keep.",
	},
	{
		Name:        "keep-monthly",
		Flag:        "keep-monthly",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of monthly backups to keep.",
	},
	{
		Name:        "keep-weekly",
		Flag:        "keep-weekly",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of weekly backups to keep.",
	},
	{
		Name:        "keep-yearly",
		Flag:        "keep-yearly",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of yearly backups to keep.",
	},
	{
		Name:        "maintenance-mode",
		Flag:        "maintenance-mode",
		Type:        "string",
		Description: "Maintenance mode, type is either 'offline' or 'read-only', message should be enclosed in \"",
	},
	{
		Name:        "notification-mode",
		Flag:        "notification-mode",
		Type:        "string",
		Default:     "notification-system",
		Enum:        []string{"legacy-sendmail", "notification-system"},
		Description: "Configure how notifications for this datastore should be sent. `legacy-sendmail` sends email notifications to the user configured in `notify-user` via the system's `sendmail` executable. `notification-system` emits matchable notification events to the notification system.",
	},
	{
		Name:        "notification-thresholds",
		Flag:        "notification-thresholds",
		Type:        "string",
		Description: "Threshold values for notifications",
	},
	{
		Name:        "notify",
		Flag:        "notify",
		Type:        "string",
		Description: "Datastore notification setting, enum can be one of 'always', 'never', or 'error'.",
	},
	{
		Name:        "notify-user",
		Flag:        "notify-user",
		Type:        "string",
		Description: "User ID",
	},
	{
		Name:        "overwrite-in-use",
		Flag:        "overwrite-in-use",
		Type:        "boolean",
		Default:     "false",
		Description: "Overwrite in use marker (S3 backed datastores only).",
	},
	{
		Name:        "path",
		Flag:        "path",
		Type:        "string",
		Description: "Either the absolute path to the datastore directory, or a relative on-device path for removable datastores.",
	},
	{
		Name:        "prune-schedule",
		Flag:        "prune-schedule",
		Type:        "string",
		Description: "Run prune job at specified schedule.",
	},
	{
		Name:        "reuse-datastore",
		Flag:        "reuse-datastore",
		Type:        "boolean",
		Default:     "false",
		Description: "Re-use existing datastore directory.",
	},
	{
		Name:        "tuning",
		Flag:        "tuning",
		Type:        "string",
		Description: "Datastore tuning options",
	},
	{
		Name:        "verify-new",
		Flag:        "verify-new",
		Type:        "boolean",
		Description: "If enabled, all new backups will be verified right after completion.",
	},
}
