// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/metrics/influxdb-udp); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// metricsInfluxdbUDPOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/metrics/influxdb-udp, in lexical order by API key.
var metricsInfluxdbUDPOptionSchemas = []optionschema.Schema{
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "enable",
		Flag:        "enable",
		Type:        "boolean",
		Default:     "true",
		Description: "Enables or disables the metrics server",
	},
	{
		Name:        "host",
		Flag:        "host",
		Type:        "string",
		Description: "host:port combination (Host can be DNS name or IP address).",
	},
	{
		Name:        "mtu",
		Flag:        "mtu",
		Type:        "integer",
		Default:     "1500",
		Description: "The MTU",
	},
}
