// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/metrics/influxdb-http); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// metricsInfluxdbHTTPOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/metrics/influxdb-http, in lexical order by API key.
var metricsInfluxdbHTTPOptionSchemas = []optionschema.Schema{
	{
		Name:        "bucket",
		Flag:        "bucket",
		Type:        "string",
		Default:     "proxmox",
		Description: "InfluxDB Bucket.",
	},
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "enable",
		Flag:        "enable",
		Type:        "boolean",
		Default:     "true",
		Description: "Enables or disables the metrics server",
	},
	{
		Name:        "max-body-size",
		Flag:        "max-body-size",
		Type:        "integer",
		Default:     "25000000",
		Description: "The (optional) maximum body size",
	},
	{
		Name:        "organization",
		Flag:        "organization",
		Type:        "string",
		Default:     "proxmox",
		Description: "InfluxDB Organization.",
	},
	{
		Name:        "url",
		Flag:        "url",
		Type:        "string",
		Description: "HTTP(s) url with optional port.",
	},
	{
		Name:        "verify-tls",
		Flag:        "verify-tls",
		Type:        "boolean",
		Default:     "true",
		Description: "If true, the certificate will be validated.",
	},
}
