// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 PUT /nodes/{node}/config); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/pmx-cli/internal/optionschema"

// nodeConfigOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// PUT /nodes/{node}/config, in lexical order by API key.
var nodeConfigOptionSchemas = []optionschema.Schema{
	{
		Name:        "acme",
		Flag:        "acme",
		Type:        "string",
		Description: "The acme account to use on this node.",
	},
	{
		Name:        "acmedomain0",
		Flag:        "acmedomain0",
		Type:        "string",
		Description: "ACME domain configuration string",
	},
	{
		Name:        "acmedomain1",
		Flag:        "acmedomain1",
		Type:        "string",
		Description: "ACME domain configuration string",
	},
	{
		Name:        "acmedomain2",
		Flag:        "acmedomain2",
		Type:        "string",
		Description: "ACME domain configuration string",
	},
	{
		Name:        "acmedomain3",
		Flag:        "acmedomain3",
		Type:        "string",
		Description: "ACME domain configuration string",
	},
	{
		Name:        "acmedomain4",
		Flag:        "acmedomain4",
		Type:        "string",
		Description: "ACME domain configuration string",
	},
	{
		Name:        "ciphers-tls-1.2",
		Flag:        "ciphers-tls-1.2",
		Type:        "string",
		Description: "OpenSSL cipher list used by the proxy for TLS <= 1.2",
	},
	{
		Name:        "ciphers-tls-1.3",
		Flag:        "ciphers-tls-1.3",
		Type:        "string",
		Description: "OpenSSL ciphersuites list used by the proxy for TLS 1.3",
	},
	{
		Name:        "consent-text",
		Flag:        "consent-text",
		Type:        "string",
		Description: "Consent banner text",
	},
	{
		Name:        "default-lang",
		Flag:        "default-lang",
		Type:        "string",
		Enum:        []string{"ar", "ca", "da", "de", "en", "es", "eu", "fa", "fr", "gl", "he", "hu", "it", "ja", "kr", "nb", "nl", "nn", "pl", "pt_BR", "ru", "sl", "sv", "tr", "zh_CN", "zh_TW"},
		Description: "All available languages in Proxmox. Taken from proxmox-i18n repository. pt_BR, zh_CN, and zh_TW use the same case in the translation files.",
	},
	{
		Name:        "description",
		Flag:        "description",
		Type:        "string",
		Description: "Comment (multiple lines).",
	},
	{
		Name:        "email-from",
		Flag:        "email-from",
		Type:        "string",
		Description: "E-Mail Address.",
	},
	{
		Name:        "http-proxy",
		Flag:        "http-proxy",
		Type:        "string",
		Description: "HTTP proxy configuration [http://]<host>[:port]",
	},
	{
		Name:        "location",
		Flag:        "location",
		Type:        "string",
		Description: "The location of the PBS instance.",
	},
	{
		Name:        "task-log-max-days",
		Flag:        "task-log-max-days",
		Type:        "integer",
		Minimum:     "0",
		Description: "Maximum days to keep Task logs",
	},
}
