// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/notifications/endpoints/smtp); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// notifSmtpOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/notifications/endpoints/smtp, in lexical order by API key.
var notifSmtpOptionSchemas = []optionschema.Schema{
	{
		Name:        "author",
		Flag:        "author",
		Type:        "string",
		Description: "Author of the mail. Defaults to 'Proxmox Backup Server ($hostname)'",
	},
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "disable",
		Flag:        "disable",
		Type:        "boolean",
		Description: "Disable this target.",
	},
	{
		Name:        "from-address",
		Flag:        "from-address",
		Type:        "string",
		Description: "`From` address for the mail. SMTP relays might require that this address is owned by the user in order to avoid spoofing. The `From` header in the email will be set to `$author <$from-address>`.",
	},
	{
		Name:        "mailto",
		Flag:        "mailto",
		Type:        "array",
		Description: "Mail address to send a mail to.",
	},
	{
		Name:        "mailto-user",
		Flag:        "mailto-user",
		Type:        "array",
		Description: "Users to send a mail to. The email address of the user will be looked up in users.cfg.",
	},
	{
		Name:        "mode",
		Flag:        "mode",
		Type:        "string",
		Default:     "tls",
		Enum:        []string{"insecure", "starttls", "tls"},
		Description: "Connection security",
	},
	{
		Name:        "origin",
		Flag:        "origin",
		Type:        "string",
		Enum:        []string{"user-created", "builtin", "modified-builtin"},
		Description: "The origin of a notification configuration entry.",
	},
	{
		Name:        "port",
		Flag:        "port",
		Type:        "integer",
		Minimum:     "0",
		Maximum:     "65535",
		Description: "The port to connect to. If not set, the used port defaults to 25 (insecure), 465 (tls) or 587 (starttls), depending on the value of mode",
	},
	{
		Name:        "server",
		Flag:        "server",
		Type:        "string",
		Description: "Host name or IP of the SMTP relay.",
	},
	{
		Name:        "username",
		Flag:        "username",
		Type:        "string",
		Description: "Username to use during authentication. If no username is set, no authentication will be performed. The PLAIN and LOGIN authentication methods are supported",
	},
}
