// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/notifications/endpoints/gotify); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/pmx-cli/internal/optionschema"

// notifGotifyOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/notifications/endpoints/gotify, in lexical order by API key.
var notifGotifyOptionSchemas = []optionschema.Schema{
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "disable",
		Flag:        "disable",
		Type:        "boolean",
		Description: "Disable this target.",
	},
	{
		Name:        "filter",
		Flag:        "filter",
		Type:        "string",
		Description: "Deprecated.",
	},
	{
		Name:        "origin",
		Flag:        "origin",
		Type:        "string",
		Enum:        []string{"user-created", "builtin", "modified-builtin"},
		Description: "The origin of a notification configuration entry.",
	},
	{
		Name:        "server",
		Flag:        "server",
		Type:        "string",
		Description: "Gotify Server URL.",
	},
}
