// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/notifications/endpoints/webhook); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// notifWebhookOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/notifications/endpoints/webhook, in lexical order by API key.
var notifWebhookOptionSchemas = []optionschema.Schema{
	{
		Name:        "body",
		Flag:        "body",
		Type:        "string",
		Description: "The HTTP body to send. Supports templating.",
	},
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "disable",
		Flag:        "disable",
		Type:        "boolean",
		Description: "Disable this target.",
	},
	{
		Name:        "header",
		Flag:        "header",
		Type:        "array",
		Description: "Array of HTTP headers. Each entry is a property string with a name and a value. The value property contains the header in base64 encoding. Supports templating.",
	},
	{
		Name:        "method",
		Flag:        "method",
		Type:        "string",
		Default:     "post",
		Enum:        []string{"post", "put", "get"},
		Description: "HTTP Method to use.",
	},
	{
		Name:        "origin",
		Flag:        "origin",
		Type:        "string",
		Enum:        []string{"user-created", "builtin", "modified-builtin"},
		Description: "The origin of a notification configuration entry.",
	},
	{
		Name:        "url",
		Flag:        "url",
		Type:        "string",
		Description: "HTTP(s) url with optional port.",
	},
}
