// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/notifications/matchers); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/pmx-cli/internal/optionschema"

// notifMatcherOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/notifications/matchers, in lexical order by API key.
var notifMatcherOptionSchemas = []optionschema.Schema{
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "disable",
		Flag:        "disable",
		Type:        "boolean",
		Description: "Disable this matcher.",
	},
	{
		Name:        "invert-match",
		Flag:        "invert-match",
		Type:        "boolean",
		Description: "Invert match of the whole filter.",
	},
	{
		Name:        "match-calendar",
		Flag:        "match-calendar",
		Type:        "array",
		Description: "List of matched severity levels.",
	},
	{
		Name:        "match-field",
		Flag:        "match-field",
		Type:        "array",
		Description: "List of matched metadata fields.",
	},
	{
		Name:        "match-severity",
		Flag:        "match-severity",
		Type:        "array",
		Description: "List of matched severity levels.",
	},
	{
		Name:        "mode",
		Flag:        "mode",
		Type:        "string",
		Default:     "all",
		Enum:        []string{"all", "any"},
		Description: "The mode in which the results of matches are combined.",
	},
	{
		Name:        "origin",
		Flag:        "origin",
		Type:        "string",
		Enum:        []string{"user-created", "builtin", "modified-builtin"},
		Description: "The origin of a notification configuration entry.",
	},
	{
		Name:        "target",
		Flag:        "target",
		Type:        "array",
		Description: "Targets to notify.",
	},
}
