// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/notifications/endpoints/sendmail); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/pmx-cli/internal/optionschema"

// notifSendmailOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/notifications/endpoints/sendmail, in lexical order by API key.
var notifSendmailOptionSchemas = []optionschema.Schema{
	{
		Name:        "author",
		Flag:        "author",
		Type:        "string",
		Description: "Author of the mail. Defaults to 'Proxmox Backup Server ($hostname)'",
	},
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "disable",
		Flag:        "disable",
		Type:        "boolean",
		Description: "Disable this target.",
	},
	{
		Name:        "filter",
		Flag:        "filter",
		Type:        "string",
		Description: "Deprecated.",
	},
	{
		Name:        "from-address",
		Flag:        "from-address",
		Type:        "string",
		Description: "`From` address for sent E-Mails. If the parameter is not set, the plugin will fall back to the email-from setting from node.cfg (PBS). If that is also not set, the plugin will default to root@$hostname, where $hostname is the hostname of the node.",
	},
	{
		Name:        "mailto",
		Flag:        "mailto",
		Type:        "array",
		Description: "Mail address to send a mail to.",
	},
	{
		Name:        "mailto-user",
		Flag:        "mailto-user",
		Type:        "array",
		Description: "Users to send a mail to. The email address of the user will be looked up in users.cfg.",
	},
	{
		Name:        "origin",
		Flag:        "origin",
		Type:        "string",
		Enum:        []string{"user-created", "builtin", "modified-builtin"},
		Description: "The origin of a notification configuration entry.",
	},
}
