// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/prune); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// pruneJobOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/prune, in lexical order by API key.
var pruneJobOptionSchemas = []optionschema.Schema{
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "disable",
		Flag:        "disable",
		Type:        "boolean",
		Default:     "false",
		Description: "Disable this job.",
	},
	{
		Name:        "keep-daily",
		Flag:        "keep-daily",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of daily backups to keep.",
	},
	{
		Name:        "keep-hourly",
		Flag:        "keep-hourly",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of hourly backups to keep.",
	},
	{
		Name:        "keep-last",
		Flag:        "keep-last",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of backups to keep.",
	},
	{
		Name:        "keep-monthly",
		Flag:        "keep-monthly",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of monthly backups to keep.",
	},
	{
		Name:        "keep-weekly",
		Flag:        "keep-weekly",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of weekly backups to keep.",
	},
	{
		Name:        "keep-yearly",
		Flag:        "keep-yearly",
		Type:        "integer",
		Minimum:     "1",
		Description: "Number of yearly backups to keep.",
	},
	{
		Name:        "max-depth",
		Flag:        "max-depth",
		Type:        "integer",
		Minimum:     "0",
		Maximum:     "7",
		Description: "How many levels of namespaces should be operated on (0 == no recursion, empty == automatic full recursion, namespace depths reduce maximum allowed value)",
	},
	{
		Name:        "ns",
		Flag:        "ns",
		Type:        "string",
		Description: "Namespace.",
	},
	{
		Name:        "schedule",
		Flag:        "schedule",
		Type:        "string",
		Description: "Run prune job at specified schedule.",
	},
	{
		Name:        "store",
		Flag:        "store",
		Type:        "string",
		Description: "Datastore name.",
	},
}
