// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/access/ldap); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/pmx-cli/internal/optionschema"

// realmLdapOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/access/ldap, in lexical order by API key.
var realmLdapOptionSchemas = []optionschema.Schema{
	{
		Name:        "base-dn",
		Flag:        "base-dn",
		Type:        "string",
		Description: "LDAP Domain",
	},
	{
		Name:        "bind-dn",
		Flag:        "bind-dn",
		Type:        "string",
		Description: "LDAP Domain",
	},
	{
		Name:        "capath",
		Flag:        "capath",
		Type:        "string",
		Description: "CA certificate to use for the server. The path can point to either a file, or a directory. If it points to a file, the PEM-formatted X.509 certificate stored at the path will be added as a trusted certificate. If the path points to a directory, the directory replaces the system's default certificate store at `/etc/ssl/certs` - Every file in the directory will be loaded as a trusted certificate.",
	},
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "default",
		Flag:        "default",
		Type:        "boolean",
		Default:     "false",
		Description: "True if you want this to be the default realm selected on login.",
	},
	{
		Name:        "filter",
		Flag:        "filter",
		Type:        "string",
		Description: "Custom LDAP search filter for user sync",
	},
	{
		Name:        "mode",
		Flag:        "mode",
		Type:        "string",
		Default:     "ldap",
		Enum:        []string{"ldap", "ldap+starttls", "ldaps"},
		Description: "LDAP connection type",
	},
	{
		Name:        "port",
		Flag:        "port",
		Type:        "integer",
		Minimum:     "0",
		Maximum:     "65535",
		Description: "Port",
	},
	{
		Name:        "server1",
		Flag:        "server1",
		Type:        "string",
		Description: "LDAP server address",
	},
	{
		Name:        "server2",
		Flag:        "server2",
		Type:        "string",
		Description: "Fallback LDAP server address",
	},
	{
		Name:        "sync-attributes",
		Flag:        "sync-attributes",
		Type:        "string",
		Description: "Comma-separated list of key=value pairs for specifying which LDAP attributes map to which PBS user field. For example, to map the LDAP attribute ``mail`` to PBS's ``email``, write ``email=mail``.",
	},
	{
		Name:        "sync-defaults-options",
		Flag:        "sync-defaults-options",
		Type:        "string",
		Description: "sync defaults options",
	},
	{
		Name:        "user-attr",
		Flag:        "user-attr",
		Type:        "string",
		Description: "Username attribute. Used to map a ``userid`` to LDAP to an LDAP ``dn``.",
	},
	{
		Name:        "user-classes",
		Flag:        "user-classes",
		Type:        "string",
		Default:     "inetorgperson,posixaccount,person,user",
		Description: "Comma-separated list of allowed objectClass values for user synchronization. For instance, if ``user-classes`` is set to ``person,user``, then user synchronization will consider all LDAP entities where ``objectClass: person`` `or` ``objectClass: user``.",
	},
	{
		Name:        "verify",
		Flag:        "verify",
		Type:        "boolean",
		Default:     "false",
		Description: "Verify server certificate",
	},
}
