// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/access/openid); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// realmOpenidOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/access/openid, in lexical order by API key.
var realmOpenidOptionSchemas = []optionschema.Schema{
	{
		Name:        "acr-values",
		Flag:        "acr-values",
		Type:        "string",
		Description: "OpenID ACR List",
	},
	{
		Name:        "audiences",
		Flag:        "audiences",
		Type:        "string",
		Description: "OpenID audience list.",
	},
	{
		Name:        "autocreate",
		Flag:        "autocreate",
		Type:        "boolean",
		Default:     "false",
		Description: "Automatically create users if they do not exist.",
	},
	{
		Name:        "client-id",
		Flag:        "client-id",
		Type:        "string",
		Description: "OpenID Client ID",
	},
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "default",
		Flag:        "default",
		Type:        "boolean",
		Default:     "false",
		Description: "True if you want this to be the default realm selected on login.",
	},
	{
		Name:        "issuer-url",
		Flag:        "issuer-url",
		Type:        "string",
		Description: "OpenID Issuer Url",
	},
	{
		Name:        "prompt",
		Flag:        "prompt",
		Type:        "string",
		Description: "OpenID Prompt",
	},
	{
		Name:        "scopes",
		Flag:        "scopes",
		Type:        "string",
		Default:     "email profile",
		Description: "OpenID Scope List",
	},
	{
		Name:        "username-claim",
		Flag:        "username-claim",
		Type:        "string",
		Description: "Use the value of this attribute/claim as unique user name. It is up to the identity provider to guarantee the uniqueness. The OpenID specification only guarantees that Subject ('sub') is unique. Also make sure that the user is not allowed to change that attribute by himself!",
	},
}
