// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/remote); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// remoteOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/remote, in lexical order by API key.
var remoteOptionSchemas = []optionschema.Schema{
	{
		Name:        "auth-id",
		Flag:        "auth-id",
		Type:        "string",
		Description: "Authentication ID",
	},
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "fingerprint",
		Flag:        "fingerprint",
		Type:        "string",
		Description: "X509 certificate fingerprint (sha256).",
	},
	{
		Name:        "host",
		Flag:        "host",
		Type:        "string",
		Description: "DNS name or IP address.",
	},
	{
		Name:        "port",
		Flag:        "port",
		Type:        "integer",
		Description: "The (optional) port",
	},
	{
		Name:        "use-node-proxy",
		Flag:        "use-node-proxy",
		Type:        "boolean",
		Default:     "false",
		Description: "Use the http proxy configuration of the node for remote connections.",
	},
}
