// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/s3); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// s3OptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/s3, in lexical order by API key.
var s3OptionSchemas = []optionschema.Schema{
	{
		Name:        "access-key",
		Flag:        "access-key",
		Type:        "string",
		Description: "Access key for S3 object store.",
	},
	{
		Name:        "burst-in",
		Flag:        "burst-in",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "burst-out",
		Flag:        "burst-out",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "endpoint",
		Flag:        "endpoint",
		Type:        "string",
		Description: "Endpoint to access S3 object store.",
	},
	{
		Name:        "fingerprint",
		Flag:        "fingerprint",
		Type:        "string",
		Description: "X509 certificate fingerprint (sha256).",
	},
	{
		Name:        "limit-active-requests",
		Flag:        "limit-active-requests",
		Type:        "integer",
		Minimum:     "0",
		Description: "Combined rate limit for PUT, POST and DELETE requests given as #request/s.",
	},
	{
		Name:        "limit-passive-requests",
		Flag:        "limit-passive-requests",
		Type:        "integer",
		Minimum:     "0",
		Description: "Combined rate limit for GET and HEAD requests given as #request/s.",
	},
	{
		Name:        "path-style",
		Flag:        "path-style",
		Type:        "boolean",
		Default:     "false",
		Description: "Use path style bucket addressing over vhost style.",
	},
	{
		Name:        "port",
		Flag:        "port",
		Type:        "integer",
		Description: "Port to access S3 object store.",
	},
	{
		Name:        "provider-quirks",
		Flag:        "provider-quirks",
		Type:        "array",
		Description: "List of provider specific feature implementation quirks.",
	},
	{
		Name:        "put-rate-limit",
		Flag:        "put-rate-limit",
		Type:        "integer",
		Description: "Rate limit for put requests given as #request/s (deprecated: use active-rate-limit instead).",
	},
	{
		Name:        "rate-in",
		Flag:        "rate-in",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "rate-out",
		Flag:        "rate-out",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "region",
		Flag:        "region",
		Type:        "string",
		Description: "Region to access S3 object store.",
	},
	{
		Name:        "use-node-proxy",
		Flag:        "use-node-proxy",
		Type:        "boolean",
		Default:     "false",
		Description: "Use node proxy for client connections",
	},
}
