// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/sync); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// syncJobOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/sync, in lexical order by API key.
var syncJobOptionSchemas = []optionschema.Schema{
	{
		Name:        "active-encryption-key",
		Flag:        "active-encryption-key",
		Type:        "string",
		Description: "ID to uniquely identify encryption/decription key",
	},
	{
		Name:        "associated-key",
		Flag:        "associated-key",
		Type:        "array",
		Description: "List of cryptographic keys associated with sync job.",
	},
	{
		Name:        "burst-in",
		Flag:        "burst-in",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "burst-out",
		Flag:        "burst-out",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "encrypted-only",
		Flag:        "encrypted-only",
		Type:        "boolean",
		Description: "Only synchronize encrypted backup snapshots, exclude others.",
	},
	{
		Name:        "group-filter",
		Flag:        "group-filter",
		Type:        "array",
		Description: "List of group filters.",
	},
	{
		Name:        "max-depth",
		Flag:        "max-depth",
		Type:        "integer",
		Minimum:     "0",
		Maximum:     "7",
		Description: "How many levels of namespaces should be operated on (0 == no recursion, empty == automatic full recursion, namespace depths reduce maximum allowed value)",
	},
	{
		Name:        "ns",
		Flag:        "ns",
		Type:        "string",
		Description: "Namespace.",
	},
	{
		Name:        "owner",
		Flag:        "owner",
		Type:        "string",
		Description: "Authentication ID",
	},
	{
		Name:        "rate-in",
		Flag:        "rate-in",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "rate-out",
		Flag:        "rate-out",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "remote",
		Flag:        "remote",
		Type:        "string",
		Description: "Remote ID.",
	},
	{
		Name:        "remote-ns",
		Flag:        "remote-ns",
		Type:        "string",
		Description: "Namespace.",
	},
	{
		Name:        "remote-store",
		Flag:        "remote-store",
		Type:        "string",
		Description: "Datastore name.",
	},
	{
		Name:        "remove-vanished",
		Flag:        "remove-vanished",
		Type:        "boolean",
		Default:     "false",
		Description: "Delete vanished backups. This removes the local copy if the remote backup was deleted.",
	},
	{
		Name:        "resync-corrupt",
		Flag:        "resync-corrupt",
		Type:        "boolean",
		Description: "If the verification failed for a local snapshot, try to pull it again.",
	},
	{
		Name:        "run-on-mount",
		Flag:        "run-on-mount",
		Type:        "boolean",
		Description: "Run this job when a relevant datastore is mounted.",
	},
	{
		Name:        "schedule",
		Flag:        "schedule",
		Type:        "string",
		Description: "Run sync job at specified schedule.",
	},
	{
		Name:        "store",
		Flag:        "store",
		Type:        "string",
		Description: "Datastore name.",
	},
	{
		Name:        "sync-direction",
		Flag:        "sync-direction",
		Type:        "string",
		Default:     "pull",
		Enum:        []string{"pull", "push"},
		Description: "Direction of the sync job, push or pull",
	},
	{
		Name:        "transfer-last",
		Flag:        "transfer-last",
		Type:        "integer",
		Minimum:     "1",
		Description: "Limit transfer to last N snapshots (per group), skipping others",
	},
	{
		Name:        "unmount-on-done",
		Flag:        "unmount-on-done",
		Type:        "boolean",
		Description: "Unmount involved removable datastore after the sync job finishes. Requires 'run-on-mount' to be enabled.",
	},
	{
		Name:        "verified-only",
		Flag:        "verified-only",
		Type:        "boolean",
		Description: "Only synchronize verified backup snapshots, exclude others.",
	},
	{
		Name:        "worker-threads",
		Flag:        "worker-threads",
		Type:        "integer",
		Default:     "1",
		Minimum:     "1",
		Maximum:     "32",
		Description: "The number of worker threads to process groups in parallel.",
	},
}
