// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/traffic-control); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// trafficOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/traffic-control, in lexical order by API key.
var trafficOptionSchemas = []optionschema.Schema{
	{
		Name:        "burst-in",
		Flag:        "burst-in",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "burst-out",
		Flag:        "burst-out",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "network",
		Flag:        "network",
		Type:        "array",
		Description: "Rule applies to Source IPs within this networks",
	},
	{
		Name:        "rate-in",
		Flag:        "rate-in",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "rate-out",
		Flag:        "rate-out",
		Type:        "string",
		Description: "Byte size with optional unit (B, KB (base 10), MB, GB, ..., KiB (base 2), MiB, Gib, ...).",
	},
	{
		Name:        "timeframe",
		Flag:        "timeframe",
		Type:        "array",
		Description: "Enable the rule at specific times",
	},
	{
		Name:        "users",
		Flag:        "users",
		Type:        "array",
		Description: "Rule applies to authenticated API requests of any of these users (overrides IP-only rules)",
	},
}
