// Code generated by cmd/optionsgen from pbs-apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 POST /config/verify); DO NOT EDIT.

package pbs

import "github.com/fivetwenty-io/pve-cli/internal/optionschema"

// verifyJobOptionSchemas describes every settable option from the Proxmox Backup Server API schema for
// POST /config/verify, in lexical order by API key.
var verifyJobOptionSchemas = []optionschema.Schema{
	{
		Name:        "comment",
		Flag:        "comment",
		Type:        "string",
		Description: "Comment.",
	},
	{
		Name:        "ignore-verified",
		Flag:        "ignore-verified",
		Type:        "boolean",
		Default:     "true",
		Description: "Do not verify backups that are already verified if their verification is not outdated.",
	},
	{
		Name:        "max-depth",
		Flag:        "max-depth",
		Type:        "integer",
		Default:     "7",
		Minimum:     "0",
		Maximum:     "7",
		Description: "How many levels of namespaces should be operated on (0 == no recursion)",
	},
	{
		Name:        "ns",
		Flag:        "ns",
		Type:        "string",
		Description: "Namespace.",
	},
	{
		Name:        "outdated-after",
		Flag:        "outdated-after",
		Type:        "integer",
		Minimum:     "0",
		Description: "Days after that a verification becomes outdated. (0 is deprecated)'",
	},
	{
		Name:        "read-threads",
		Flag:        "read-threads",
		Type:        "integer",
		Default:     "1",
		Minimum:     "1",
		Maximum:     "32",
		Description: "The number of threads to use for reading chunks in verify job.",
	},
	{
		Name:        "schedule",
		Flag:        "schedule",
		Type:        "string",
		Description: "Run verify job at specified schedule.",
	},
	{
		Name:        "store",
		Flag:        "store",
		Type:        "string",
		Description: "Datastore name.",
	},
	{
		Name:        "verify-threads",
		Flag:        "verify-threads",
		Type:        "integer",
		Default:     "4",
		Minimum:     "1",
		Maximum:     "32",
		Description: "The number of threads to use for verifying chunks in verify job.",
	},
}
