// Code generated by cmd/optionsgen from apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 PUT /cluster/firewall/options); DO NOT EDIT.

package cluster

import "github.com/fivetwenty-io/pmx-cli/internal/optionschema"

// firewallOptionSchemas describes every settable option from the PVE API schema for
// PUT /cluster/firewall/options, in lexical order by API key.
var firewallOptionSchemas = []optionschema.Schema{
	{
		Name:        "ebtables",
		Flag:        "ebtables",
		Type:        "boolean",
		Default:     "true",
		Description: "Enable ebtables rules cluster wide.",
	},
	{
		Name:        "enable",
		Flag:        "enable",
		Type:        "integer",
		Default:     "0",
		Minimum:     "0",
		Description: "Enable or disable the firewall cluster wide.",
	},
	{
		Name:        "log_ratelimit",
		Flag:        "log-ratelimit",
		Type:        "string",
		Description: "Log ratelimiting settings",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "burst",
				Type:        "integer",
				Default:     "5",
				Minimum:     "0",
				Description: "Initial burst of packages which will always get logged before the rate is applied",
			},
			{
				Name:        "enable",
				Type:        "boolean",
				Default:     "true",
				Description: "Enable or disable log rate limiting",
				Required:    true,
			},
			{
				Name:        "rate",
				Type:        "string",
				Default:     "1/second",
				Description: "Frequency with which the burst bucket gets refilled",
			},
		},
	},
	{
		Name:        "policy_forward",
		Flag:        "policy-forward",
		Type:        "string",
		Enum:        []string{"ACCEPT", "DROP"},
		Description: "Forward policy.",
	},
	{
		Name:        "policy_in",
		Flag:        "policy-in",
		Type:        "string",
		Enum:        []string{"ACCEPT", "REJECT", "DROP"},
		Description: "Input policy.",
	},
	{
		Name:        "policy_out",
		Flag:        "policy-out",
		Type:        "string",
		Enum:        []string{"ACCEPT", "REJECT", "DROP"},
		Description: "Output policy.",
	},
}
