// Code generated by cmd/optionsgen from apidoc.json (github.com/fivetwenty-io/proxmox-apiclient-go/v3 PUT /cluster/options); DO NOT EDIT.

package cluster

import "github.com/fivetwenty-io/proxmox-cli/internal/optionschema"

// optionSchemas describes every settable option from the PVE API schema for
// PUT /cluster/options, in lexical order by API key.
var optionSchemas = []optionschema.Schema{
	{
		Name:        "bwlimit",
		Flag:        "bwlimit",
		Type:        "string",
		Description: "Set I/O bandwidth limit for various operations (in KiB/s).",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "clone",
				Type:        "number",
				Minimum:     "0",
				Description: "bandwidth limit in KiB/s for cloning disks",
			},
			{
				Name:        "default",
				Type:        "number",
				Minimum:     "0",
				Description: "default bandwidth limit in KiB/s",
			},
			{
				Name:        "migration",
				Type:        "number",
				Minimum:     "0",
				Description: "bandwidth limit in KiB/s for migrating guests (including moving local disks)",
			},
			{
				Name:        "move",
				Type:        "number",
				Minimum:     "0",
				Description: "bandwidth limit in KiB/s for moving disks",
			},
			{
				Name:        "restore",
				Type:        "number",
				Minimum:     "0",
				Description: "bandwidth limit in KiB/s for restoring guests from backups",
			},
		},
	},
	{
		Name:        "consent-text",
		Flag:        "consent-text",
		Type:        "string",
		Description: "Consent text that is displayed before logging in.",
	},
	{
		Name:        "console",
		Flag:        "console",
		Type:        "string",
		Enum:        []string{"applet", "vv", "html5", "xtermjs"},
		Description: "Select the default Console viewer. You can either use the builtin java applet (VNC; deprecated and maps to html5), an external virt-viewer comtatible application (SPICE), an HTML5 based vnc viewer (noVNC), or an HTML5 based console client (xtermjs). If the selected viewer is not available (e.g. SPICE not activated for the VM), the fallback is noVNC.",
	},
	{
		Name:        "crs",
		Flag:        "crs",
		Type:        "string",
		Description: "Cluster resource scheduling settings.",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "ha",
				Type:        "string",
				Default:     "basic",
				Enum:        []string{"basic", "static", "dynamic"},
				Description: "Use this resource scheduler mode for HA.",
			},
			{
				Name:        "ha-auto-rebalance",
				Type:        "boolean",
				Default:     "false",
				Description: "Whether to use CRS for balancing HA resources automatically depending on the current node imbalance.",
			},
			{
				Name:        "ha-auto-rebalance-hold-duration",
				Type:        "number",
				Default:     "3",
				Minimum:     "0",
				Description: "The number of HA rounds for which the cluster node imbalance threshold must be exceeded before triggering an automatic resource balancing migration.",
			},
			{
				Name:        "ha-auto-rebalance-margin",
				Type:        "number",
				Default:     "10",
				Minimum:     "0",
				Maximum:     "100",
				Description: "The minimum relative improvement in cluster node imbalance, in percent, to commit to a resource balancing migration.",
			},
			{
				Name:        "ha-auto-rebalance-method",
				Type:        "string",
				Default:     "bruteforce",
				Enum:        []string{"bruteforce", "topsis"},
				Description: "The method to use for the scoring of balancing migrations.",
			},
			{
				Name:        "ha-auto-rebalance-threshold",
				Type:        "number",
				Default:     "30",
				Minimum:     "0",
				Maximum:     "100",
				Description: "The cluster node imbalance, in percent, which will trigger the automatic resource balancing system if exceeded.",
			},
			{
				Name:        "ha-rebalance-on-start",
				Type:        "boolean",
				Default:     "false",
				Description: "Set to use CRS for selecting a suited node when a HA services request-state changes from stop to start.",
			},
		},
	},
	{
		Name:        "description",
		Flag:        "description",
		Type:        "string",
		Description: "Datacenter description. Shown in the web-interface datacenter notes panel. This is saved as comment inside the configuration file.",
	},
	{
		Name:        "email_from",
		Flag:        "email-from",
		Type:        "string",
		Description: "Specify email address to send notification from (default is root@$hostname)",
	},
	{
		Name:        "fencing",
		Flag:        "fencing",
		Type:        "string",
		Default:     "watchdog",
		Enum:        []string{"watchdog", "hardware", "both"},
		Description: "Set the fencing mode of the HA cluster. Hardware mode needs a valid configuration of fence devices in /etc/pve/ha/fence.cfg. With both all two modes are used. WARNING: 'hardware' and 'both' are EXPERIMENTAL & WIP",
	},
	{
		Name:        "ha",
		Flag:        "ha",
		Type:        "string",
		Description: "Cluster wide HA settings.",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "shutdown_policy",
				Type:        "string",
				Default:     "conditional",
				Enum:        []string{"freeze", "failover", "conditional", "migrate"},
				Description: "The policy for HA services on node shutdown. 'freeze' disables auto-recovery, 'failover' ensures recovery, 'conditional' recovers on poweroff and freezes on reboot. 'migrate' will migrate running services to other nodes, if possible. With 'freeze' or 'failover', HA Services will always get stopped first on shutdown.",
				Required:    true,
			},
		},
	},
	{
		Name:        "http_proxy",
		Flag:        "http-proxy",
		Type:        "string",
		Description: "Specify external http proxy which is used for downloads (example: 'http://username:password@host:port/')",
	},
	{
		Name:        "keyboard",
		Flag:        "keyboard",
		Type:        "string",
		Enum:        []string{"de", "de-ch", "da", "en-gb", "en-us", "es", "fi", "fr", "fr-be", "fr-ca", "fr-ch", "hu", "is", "it", "ja", "lt", "mk", "nl", "no", "pl", "pt", "pt-br", "sv", "sl", "tr"},
		Description: "Default keybord layout for vnc server.",
	},
	{
		Name:        "language",
		Flag:        "language",
		Type:        "string",
		Enum:        []string{"ar", "ca", "da", "de", "en", "es", "eu", "fa", "fr", "hr", "he", "it", "ja", "ka", "kr", "nb", "nl", "nn", "pl", "pt_BR", "ru", "sl", "sv", "tr", "ukr", "zh_CN", "zh_TW"},
		Description: "Default GUI language.",
	},
	{
		Name:        "location",
		Flag:        "location",
		Type:        "string",
		Description: "The location of the cluster.",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "latitude",
				Type:        "number",
				Minimum:     "-90",
				Maximum:     "90",
				Description: "The latitude of the nodes location in degrees.",
				Required:    true,
			},
			{
				Name:        "longitude",
				Type:        "number",
				Minimum:     "-180",
				Maximum:     "180",
				Description: "The longitude of the nodes location in degrees.",
				Required:    true,
			},
			{
				Name:        "name",
				Type:        "string",
				Description: "The name of the location of this node",
			},
		},
	},
	{
		Name:        "mac_prefix",
		Flag:        "mac-prefix",
		Type:        "string",
		Default:     "BC:24:11",
		Description: "Prefix for the auto-generated MAC addresses of virtual guests. The default 'BC:24:11' is the OUI assigned by the IEEE to Proxmox Server Solutions GmbH for a 24-bit large MAC block. You're allowed to use this in local networks, i.e., those not directly reachable by the public (e.g., in a LAN or behind NAT).",
	},
	{
		Name:        "max_workers",
		Flag:        "max-workers",
		Type:        "integer",
		Minimum:     "1",
		Description: "Defines how many workers (per node) are maximal started on actions like 'stopall VMs' or task from the ha-manager.",
	},
	{
		Name:        "migration",
		Flag:        "migration",
		Type:        "string",
		Description: "For cluster wide migration settings.",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "network",
				Type:        "string",
				Description: "CIDR of the (sub) network that is used for migration. Used as a fallback for replications jobs if the replication network setting is not set",
			},
			{
				Name:        "type",
				Type:        "string",
				Default:     "secure",
				Enum:        []string{"secure", "insecure"},
				Description: "Migration traffic is encrypted using an SSH tunnel by default. On secure, completely private networks this can be disabled to increase performance.",
				Required:    true,
			},
		},
	},
	{
		Name:        "migration_unsecure",
		Flag:        "migration-unsecure",
		Type:        "boolean",
		Description: "Migration is secure using SSH tunnel by default. For secure private networks you can disable it to speed up migration. Deprecated, use the 'migration' property instead!",
	},
	{
		Name:        "next-id",
		Flag:        "next-id",
		Type:        "string",
		Description: "Control the range for the free VMID auto-selection pool.",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "lower",
				Type:        "integer",
				Default:     "100",
				Description: "Lower, inclusive boundary for free next-id API range.",
			},
			{
				Name:        "upper",
				Type:        "integer",
				Default:     "1000000",
				Description: "Upper, exclusive boundary for free next-id API range.",
			},
		},
	},
	{
		Name:        "notify",
		Flag:        "notify",
		Type:        "string",
		Description: "Cluster-wide notification settings.",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "fencing",
				Type:        "string",
				Enum:        []string{"always", "never"},
				Description: "UNUSED - Use datacenter notification settings instead.",
			},
			{
				Name:        "package-updates",
				Type:        "string",
				Default:     "auto",
				Enum:        []string{"auto", "always", "never"},
				Description: "DEPRECATED: Use datacenter notification settings instead. Control when the daily update job should send out notifications.",
			},
			{
				Name:        "replication",
				Type:        "string",
				Enum:        []string{"always", "never"},
				Description: "UNUSED - Use datacenter notification settings instead.",
			},
			{
				Name:        "target-fencing",
				Type:        "string",
				Description: "UNUSED - Use datacenter notification settings instead.",
			},
			{
				Name:        "target-package-updates",
				Type:        "string",
				Description: "UNUSED - Use datacenter notification settings instead.",
			},
			{
				Name:        "target-replication",
				Type:        "string",
				Description: "UNUSED - Use datacenter notification settings instead.",
			},
		},
	},
	{
		Name:        "registered-tags",
		Flag:        "registered-tags",
		Type:        "string",
		Description: "A list of tags that require a `Sys.Modify` on '/' to set and delete. Tags set here that are also in 'user-tag-access' also require `Sys.Modify`.",
	},
	{
		Name:        "replication",
		Flag:        "replication",
		Type:        "string",
		Description: "For cluster wide replication settings.",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "network",
				Type:        "string",
				Description: "CIDR of the (sub) network that is used for replication jobs.",
			},
			{
				Name:        "type",
				Type:        "string",
				Default:     "secure",
				Enum:        []string{"secure", "insecure"},
				Description: "Replication traffic is encrypted using an SSH tunnel by default. On secure, completely private networks this can be disabled to increase performance.",
				Required:    true,
			},
		},
	},
	{
		Name:        "tag-style",
		Flag:        "tag-style",
		Type:        "string",
		Description: "Tag style options.",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "case-sensitive",
				Type:        "boolean",
				Default:     "false",
				Description: "Controls if filtering for unique tags on update should check case-sensitive.",
			},
			{
				Name:        "color-map",
				Type:        "string",
				Description: "Manual color mapping for tags (semicolon separated).",
			},
			{
				Name:        "ordering",
				Type:        "string",
				Default:     "alphabetical",
				Enum:        []string{"config", "alphabetical"},
				Description: "Controls the sorting of the tags in the web-interface and the API update.",
			},
			{
				Name:        "shape",
				Type:        "string",
				Default:     "circle",
				Enum:        []string{"full", "circle", "dense", "none"},
				Description: "Tag shape for the web ui tree. 'full' draws the full tag. 'circle' draws only a circle with the background color. 'dense' only draws a small rectancle (useful when many tags are assigned to each guest).'none' disables showing the tags.",
			},
		},
	},
	{
		Name:        "u2f",
		Flag:        "u2f",
		Type:        "string",
		Description: "u2f",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "appid",
				Type:        "string",
				Description: "U2F AppId URL override. Defaults to the origin.",
			},
			{
				Name:        "origin",
				Type:        "string",
				Description: "U2F Origin override. Mostly useful for single nodes with a single URL.",
			},
		},
	},
	{
		Name:        "user-tag-access",
		Flag:        "user-tag-access",
		Type:        "string",
		Description: "Privilege options for user-settable tags",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "user-allow",
				Type:        "string",
				Default:     "free",
				Enum:        []string{"none", "list", "existing", "free"},
				Description: "Controls tag usage for users without `Sys.Modify` on `/` by either allowing `none`, a `list`, already `existing` or anything (`free`).",
			},
			{
				Name:        "user-allow-list",
				Type:        "string",
				Description: "List of tags users are allowed to set and delete (semicolon separated) for 'user-allow' values 'list' and 'existing'.",
			},
		},
	},
	{
		Name:        "webauthn",
		Flag:        "webauthn",
		Type:        "string",
		Description: "webauthn configuration",
		SubKeys: []optionschema.SubKey{
			{
				Name:        "allow-subdomains",
				Type:        "boolean",
				Default:     "true",
				Description: "Whether to allow the origin to be a subdomain, rather than the exact URL.",
			},
			{
				Name:        "id",
				Type:        "string",
				Description: "Relying party ID. Must be the domain name without protocol, port or location. Changing this *will* break existing credentials.",
			},
			{
				Name:        "origin",
				Type:        "string",
				Description: "Site origin. Must be a `https://` URL (or `http://localhost`). Should contain the address users type in their browsers to access the web interface. Changing this *may* break existing credentials.",
			},
			{
				Name:        "rp",
				Type:        "string",
				Description: "Relying party name. Any text identifier. Changing this *may* break existing credentials.",
			},
		},
	},
}
