package cluster

//go:generate go run github.com/fivetwenty-io/pve-cli/cmd/optionsgen -out options_schema_gen.go

import (
	"sort"
	"strings"
)

// optionSubKey describes one sub-key of a dict-encoded datacenter option
// (for example migration's "type" and "network").
type optionSubKey struct {
	// Name is the sub-key as written inside the option value.
	Name string `json:"name"`
	// Type is the schema type (string, boolean, number, integer).
	Type string `json:"type"`
	// Default is the built-in default applied when the sub-key is unset.
	Default string `json:"default,omitempty"`
	// Enum lists the allowed values, when the schema constrains them.
	Enum []string `json:"values,omitempty"`
	// Description is the schema description, whitespace-normalised.
	Description string `json:"description,omitempty"`
	// Required marks sub-keys that must be present when the option is set.
	Required bool `json:"required,omitempty"`
}

// optionSchema describes one settable datacenter option from the PVE API
// schema for PUT /cluster/options. The table itself (optionSchemas) is
// generated by cmd/optionsgen — see options_schema_gen.go.
type optionSchema struct {
	// Name is the API parameter / datacenter.cfg key (e.g. "mac_prefix").
	Name string `json:"name"`
	// Flag is the CLI flag spelling (e.g. "mac-prefix").
	Flag string `json:"flag"`
	// Type is the schema type (string, boolean, integer).
	Type string `json:"type"`
	// Default is the built-in default applied when the option is unset.
	Default string `json:"default,omitempty"`
	// Enum lists the allowed values, when the schema constrains them.
	Enum []string `json:"values,omitempty"`
	// Description is the schema description, whitespace-normalised.
	Description string `json:"description,omitempty"`
	// SubKeys describes the components of dict-encoded option values.
	SubKeys []optionSubKey `json:"sub_keys,omitempty"`
}

// findOptionSchema returns the schema whose API name or flag spelling matches,
// or nil when the option is unknown.
func findOptionSchema(nameOrFlag string) *optionSchema {
	for i := range optionSchemas {
		if optionSchemas[i].Name == nameOrFlag || optionSchemas[i].Flag == nameOrFlag {
			return &optionSchemas[i]
		}
	}
	return nil
}

// schemaSuffix builds the generated tail appended to a set flag's help text:
// allowed values and default for scalar options, the sub-key list for
// dict-encoded options.
func (s *optionSchema) schemaSuffix() string {
	var parts []string
	if len(s.Enum) > 0 {
		parts = append(parts, "values: "+strings.Join(s.Enum, ", "))
	}
	if s.Default != "" {
		parts = append(parts, "default: "+s.Default)
	}
	if len(s.SubKeys) > 0 {
		keys := make([]string, len(s.SubKeys))
		for i, sk := range s.SubKeys {
			keys[i] = sk.Name
		}
		parts = append(parts, "keys: "+strings.Join(keys, ", "))
	}
	if len(parts) == 0 {
		return ""
	}
	return " (" + strings.Join(parts, "; ") + ")"
}

// defaultValue returns the value an unset option effectively has: the scalar
// default, or for dict-encoded options the composition of every sub-key that
// carries a default (e.g. migration → "type=secure"). Empty when the schema
// defines no default at all.
func (s *optionSchema) defaultValue() string {
	if s.Default != "" {
		return s.Default
	}
	var parts []string
	for _, sk := range s.SubKeys {
		if sk.Default != "" {
			parts = append(parts, sk.Name+"="+sk.Default)
		}
	}
	sort.Strings(parts)
	return strings.Join(parts, ",")
}
